# This is a basic workflow that is manually triggered

name: ' 🚀 Publish to Marketplace'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
        - name: Publish
          if: success() && startsWith(github.ref, 'refs/tags/')
          run: npm run deploy
          env:
            VSCE_PAT: ${{ secrets.VSCE_PAT }}
